version: "2"
services:
    webserver:
        build: ./Docker/php/
        ports: 
            - "80:80"
        volumes:
            - .:/var/www/html/
        links:
            - database
        networks:
            - default
        environment:
          XDEBUG_CONFIG: remote_host=127.0.0.1
    database:
        image: mysql:5.7
        ports: 
            - "3306:3306"
        environment:
            MYSQL_DATABASE: myDb
            MYSQL_USER: hexacore
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
        #volumes:
            #- ./dump:/docker-entrypoint-initdb.d
            #- persistent:/var/lib/mysql
        networks:
            - default