name: Unit Test

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: test
        run: |
          cd ${GITHUB_WORKSPACE}
          php -S localhost:80 -t public/
          cd System/Tests/
          phpunit --bootstrap autoload.php --configuration ../phpunit.xml
